### ISSUE TITLE
Can't create SSO user

### ISSUE THREAD

**Issue by AngelAlvarado** [AngelAlvarado/multiple_idp_simplesamlphp#2]
This is the log message: Unable to register user@domain using simplesamlphp_auth no customer id attribute was provided

**Comment by pablo-tapia** [comment]
Hey!

The issue is because of this part:

`if (NULL !== $simplesamlphp_authsource && isset($simplesamlphp_authsource->user_customer_id)) {`

This line cover a specific requirement from our side but we don't need to do that for other users, removing the validation should take of the issue. I can do that and update the code on the repository.

**Comment by AngelAlvarado** [comment]
Fixed by PR/commit [02369e3d](https://github.com/AngelAlvarado/multiple_idp_simplesamlphp/commit/02369e3dad3e93272febfb2b247e88b289cc0d4f). Thanks @pablo-tapia.
